# Generated by Django 5.2.15 on 2026-08-14 22:11

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_no', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('INTERSEX', 'Intersex'), ('UNKNOWN', 'Unknown'), ('NOT_STATED', 'Not stated')], default='NOT_STATED', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DECEASED', 'Deceased'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('deceased_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.CharField(choices=[('TREATMENT', 'Treatment'), ('DATA_PROCESSING', 'Data processing'), ('COMMUNICATION', 'Communication')], max_length=30)),
                ('status', models.CharField(choices=[('GRANTED', 'Granted'), ('WITHDRAWN', 'Withdrawn')], default='GRANTED', max_length=20)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('notice_version', models.CharField(blank=True, max_length=50)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=40)),
                ('is_primary', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientIdentifier',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], max_length=30)),
                ('value', models.CharField(max_length=150)),
                ('normalized_value', models.CharField(max_length=150)),
                ('verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientLink',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_type', models.CharField(choices=[('SUSPECTED_DUPLICATE', 'Suspected duplicate'), ('RELATED', 'Related'), ('EMERGENCY_CONTACT', 'Emergency contact')], max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='OPEN', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_patient_links', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_patient_links', to=settings.AUTH_USER_MODEL)),
                ('source_patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_links', to='patients.patient')),
                ('target_patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_links', to='patients.patient')),
            ],
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organisation', 'last_name', 'first_name'], name='patients_pa_organis_6303a8_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organisation', 'phone'], name='patients_pa_organis_f2d604_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('organisation', 'patient_no'), name='uniq_patient_org_no'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifier',
            constraint=models.UniqueConstraint(fields=('organisation', 'identifier_type', 'normalized_value'), name='uniq_patient_identifier_org_value'),
        ),
        migrations.AddConstraint(
            model_name='patientlink',
            constraint=models.UniqueConstraint(fields=('organisation', 'source_patient', 'target_patient', 'link_type'), name='uniq_patient_link'),
        ),
    ]
