# Generated by Django 5.2.17 on 2026-09-03 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='dob_estimated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='estimated_age_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='estimated_age_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='identity_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PROVISIONAL', 'Provisional'), ('MERGED', 'Merged')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_patients', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='patient',
            name='parish',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='sub_county',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='village',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
