# Generated by Django 5.2.15 on 2026-08-14 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='queue_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter', to='scheduling.queueentry'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='clinical.encounter'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='clinical.encounter'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='clinical.encounter'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.facility'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='clinical.encounter'),
        ),
        migrations.AddField(
            model_name='referral',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.facility'),
        ),
        migrations.AddField(
            model_name='referral',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation'),
        ),
        migrations.AddField(
            model_name='triageassessment',
            name='assessed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triageassessment',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.facility'),
        ),
        migrations.AddField(
            model_name='triageassessment',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation'),
        ),
        migrations.AddField(
            model_name='triageassessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triage_assessments', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='triageassessment',
            name='queue_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='triage_assessment', to='scheduling.queueentry'),
        ),
        migrations.AddField(
            model_name='vitalsobservation',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vitals', to='clinical.encounter'),
        ),
        migrations.AddField(
            model_name='vitalsobservation',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.facility'),
        ),
        migrations.AddField(
            model_name='vitalsobservation',
            name='measured_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitalsobservation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation'),
        ),
        migrations.AddField(
            model_name='vitalsobservation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vitals', to='patients.patient'),
        ),
        migrations.AddConstraint(
            model_name='clinicalnoteversion',
            constraint=models.UniqueConstraint(fields=('note', 'version_number'), name='uniq_note_version'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.UniqueConstraint(fields=('organisation', 'encounter_no'), name='uniq_encounter_org_no'),
        ),
    ]
