# Generated by Django 5.2.15 on 2026-08-23 07:47

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def reconcile_existing_active_allergies(apps, schema_editor):
    Allergy = apps.get_model("clinical", "Allergy")
    PatientAllergyState = apps.get_model("clinical", "PatientAllergyState")
    scopes = Allergy.objects.filter(status="ACTIVE").values(
        "organisation_id", "facility_id", "patient_id"
    ).distinct()
    for scope in scopes.iterator():
        PatientAllergyState.objects.get_or_create(
            organisation_id=scope["organisation_id"],
            facility_id=scope["facility_id"],
            patient_id=scope["patient_id"],
            defaults={"status": "RECORDED", "revision": 1},
        )

class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_encounter_complaints'),
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='entered_in_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allergy',
            name='entered_in_error_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allergies_entered_in_error', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allergy',
            name='entered_in_error_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='allergy',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='allergies_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='allergies_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_allergy_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='allergies_reviewed_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='severity',
            field=models.CharField(blank=True, choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=30),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ENTERED_IN_ERROR', 'Entered in error')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientAllergyState',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_RECORDED', 'Not recorded'), ('NKA', 'No known allergies'), ('UNKNOWN', 'Unknown'), ('RECORDED', 'Recorded allergies')], default='NOT_RECORDED', max_length=20)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergy_states', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_patient_allergy_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'facility', 'patient'), name='uniq_patient_allergy_state_scope')],
            },
        ),
        migrations.RunPython(reconcile_existing_active_allergies, reverse_code=migrations.RunPython.noop),
    ]
