# Generated by Django 5.2.15 on 2026-08-23 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



def migrate_legacy_diagnoses(apps, schema_editor):
    Diagnosis = apps.get_model("clinical", "Diagnosis")
    seen_encounters = set()
    rows = Diagnosis.objects.all().order_by("encounter_id", "created_at", "id")
    for diagnosis in rows.iterator():
        diagnosis.diagnosis_type = "FINAL"
        diagnosis.coded = bool((diagnosis.code or "").strip())
        diagnosis.is_primary = diagnosis.status == "ACTIVE" and diagnosis.encounter_id not in seen_encounters
        if diagnosis.is_primary:
            seen_encounters.add(diagnosis.encounter_id)
        diagnosis.save(update_fields=["diagnosis_type", "coded", "is_primary"])

class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_allergy_entered_in_error_at_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='certainty_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='coded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_type',
            field=models.CharField(choices=[('WORKING', 'Working diagnosis'), ('FINAL', 'Final diagnosis'), ('NO_DIAGNOSIS', 'No diagnosis')], default='FINAL', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='no_diagnosis_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20),
        ),
        migrations.RunPython(migrate_legacy_diagnoses, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.UniqueConstraint(condition=models.Q(('diagnosis_type', 'FINAL'), ('is_primary', True), ('status', 'ACTIVE')), fields=('encounter',), name='uniq_active_primary_final_diagnosis'),
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.UniqueConstraint(condition=models.Q(('diagnosis_type', 'NO_DIAGNOSIS'), ('status', 'ACTIVE')), fields=('encounter',), name='uniq_active_no_diagnosis'),
        ),
    ]
