# Generated by Django 5.2.15 on 2026-08-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_diagnosis_certainty_note_diagnosis_coded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='disposition',
            field=models.CharField(blank=True, choices=[('TREATED_AND_DISCHARGED', 'Treated and discharged'), ('REVIEW_SCHEDULED', 'Review scheduled'), ('REFERRED_OUT', 'Referred out'), ('ADMITTED_ELSEWHERE', 'Admitted elsewhere'), ('LEFT_AGAINST_ADVICE', 'Left against advice'), ('DECEASED', 'Deceased'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='disposition_note',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
