# Generated by Django 5.2.17 on 2026-09-03 23:34

import core.clock
import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def apply_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in ("billing_pricelist", "billing_visitpayerbinding"):
            cursor.execute(
                f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;"
                f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;"
                f"DROP POLICY IF EXISTS clinicopus_tenant_isolation ON {table};"
                f"CREATE POLICY clinicopus_tenant_isolation ON {table} "
                "USING (organisation_id = current_setting('app.current_org_id')::uuid) "
                "WITH CHECK (organisation_id = current_setting('app.current_org_id')::uuid);"
            )


def reverse_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in ("billing_pricelist", "billing_visitpayerbinding"):
            cursor.execute(
                f"DROP POLICY IF EXISTS clinicopus_tenant_isolation ON {table};"
                f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;"
                f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('clinical', '0008_s00_tenant_rls_repair'),
        ('patients', '0002_s01_registration_visit_checkin'),
        ('scheduling', '0003_s01_registration_visit_checkin'),
        ('tenancy', '0003_s01_registration_visit_checkin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stable_code', models.CharField(default='STANDARD', max_length=60)),
                ('name', models.CharField(max_length=160)),
                ('payer_type', models.CharField(choices=[('CASH', 'Cash'), ('SELF_PAY_MOMO', 'Self-pay mobile money')], max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VisitPayerBinding',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer_type', models.CharField(choices=[('CASH', 'Cash'), ('SELF_PAY_MOMO', 'Self-pay mobile money')], max_length=30)),
                ('binding_version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('bound_at', models.DateTimeField(default=core.clock.now)),
                ('source_event_id', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='current_line_set_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='scheduling.visit'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_invoice_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='line_set_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='source_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='source_line_identity',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='source_type',
            field=models.CharField(default='LEGACY', max_length=40),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='source_version',
            field=models.CharField(default='v1', max_length=40),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='state',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='void_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('VOID', 'Void'), ('VOIDED', 'Voided')], default='DRAFT', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('visit__isnull', False), models.Q(('status__in', ['VOID', 'VOIDED']), _negated=True)), fields=('organisation', 'facility', 'visit'), name='uniq_active_visit_invoice'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('source_line_identity__gt', '')), fields=('invoice', 'line_set_version', 'source_line_identity', 'source_version'), name='uniq_invoice_source_line_version'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation'),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_prices', to='billing.pricelist'),
        ),
        migrations.AddField(
            model_name='visitpayerbinding',
            name='bound_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitpayerbinding',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer_bindings', to='tenancy.facility'),
        ),
        migrations.AddField(
            model_name='visitpayerbinding',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation'),
        ),
        migrations.AddField(
            model_name='visitpayerbinding',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit_bindings', to='billing.pricelist'),
        ),
        migrations.AddField(
            model_name='visitpayerbinding',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseding_bindings', to='billing.visitpayerbinding'),
        ),
        migrations.AddField(
            model_name='visitpayerbinding',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer_bindings', to='scheduling.visit'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('organisation', 'stable_code', 'version'), name='uniq_price_list_org_code_version'),
        ),
        migrations.AddConstraint(
            model_name='visitpayerbinding',
            constraint=models.UniqueConstraint(fields=('visit', 'binding_version'), name='uniq_visit_payer_binding_version'),
        ),
        migrations.AddConstraint(
            model_name='visitpayerbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('visit',), name='uniq_active_visit_payer_binding'),
        ),
        migrations.RunPython(apply_rls, reverse_rls),
    ]
