// Transport shapes are generated from the Django OpenAPI contract.
export type {
  ActiveAllergy,
  ArrivalEnquiryResponse,
  ClinicalNote,
  ClinicalNoteContent,
  ComplaintDurationUnit,
  Department,
  DepartmentEnvelope,
  Diagnosis,
  DiagnosisType,
  Encounter,
  EncounterDisposition,
  FollowUpRecommendation,
  Invoice,
  InvoiceItem,
  Patient,
  PatientCheckInSummary,
  PatientDuplicateCandidate,
  PatientRegisterResponse,
  Payment,
  PresentingComplaint,
  QueueEntry,
  Receipt,
  Service,
  Visit,
  VisitCancelErrorResponse,
  VisitCheckInResponse,
  VisitContextResponse,
} from "../../generated/api-client";

export type AllergyStatus = import("../../generated/api-client").Encounter["allergy_status"];
