# Generated by Django 5.2.15 on 2026-08-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuprecommendation',
            name='interval_unit',
            field=models.CharField(blank=True, choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='followuprecommendation',
            name='interval_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
