# Generated by Django 5.2.17 on 2026-09-03 23:34

import core.clock
import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def apply_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in ("scheduling_visit", "scheduling_arrivalenquiry"):
            cursor.execute(
                f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;"
                f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;"
                f"DROP POLICY IF EXISTS clinicopus_tenant_isolation ON {table};"
                f"CREATE POLICY clinicopus_tenant_isolation ON {table} "
                "USING (organisation_id = current_setting('app.current_org_id')::uuid) "
                "WITH CHECK (organisation_id = current_setting('app.current_org_id')::uuid);"
            )


def reverse_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in ("scheduling_visit", "scheduling_arrivalenquiry"):
            cursor.execute(
                f"DROP POLICY IF EXISTS clinicopus_tenant_isolation ON {table};"
                f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;"
                f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_s01_registration_visit_checkin'),
        ('scheduling', '0002_followuprecommendation_interval_unit_and_more'),
        ('tenancy', '0003_s01_registration_visit_checkin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='hold_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='priority',
            field=models.CharField(default='ROUTINE', max_length=20),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='priority_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='priority_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='queue_time',
            field=models.DateTimeField(default=core.clock.now),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='queue_type',
            field=models.CharField(default='TRIAGE', max_length=40),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='source_event_id',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='work_identity',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('WAITING_PAYMENT', 'Waiting for payment'), ('ON_HOLD', 'On hold'), ('READY_TO_RESUME', 'Ready to resume'), ('CALLED', 'Called'), ('IN_TRIAGE', 'In triage'), ('TRIAGED', 'Triaged'), ('IN_CONSULTATION', 'In consultation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=30),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_service_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('OUTPATIENT_NEW', 'Outpatient new'), ('OUTPATIENT_REVIEW', 'Outpatient review'), ('ANC', 'ANC'), ('LAB_ONLY', 'Lab only'), ('PHARMACY_ONLY', 'Pharmacy only'), ('FOLLOW_UP_RESULTS', 'Follow-up results')], max_length=40)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('CLOSED', 'Closed'), ('CANCELLED_ERROR', 'Cancelled in error')], default='OPEN', max_length=30)),
                ('closure_reason', models.CharField(blank=True, max_length=120)),
                ('reason_for_visit', models.CharField(blank=True, max_length=120)),
                ('opened_at', models.DateTimeField(default=core.clock.now)),
                ('in_progress_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('payer_binding_id', models.UUIDField(blank=True, null=True)),
                ('emergency_setup_pending', models.BooleanField(default=False)),
                ('slip_print_count', models.PositiveIntegerField(default=0)),
                ('referral_source_type', models.CharField(choices=[('SELF', 'Self'), ('REFERRED_FACILITY', 'Referred facility'), ('REFERRED_PERSON', 'Referred person'), ('CAMP_OUTREACH', 'Camp/outreach'), ('WALK_BY', 'Walk-by')], default='SELF', max_length=30)),
                ('referral_source_name', models.CharField(blank=True, max_length=100)),
                ('results_review', models.BooleanField(default=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_visits', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.facility')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_visits', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
                ('related_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_visits', to='scheduling.visit')),
            ],
        ),
        migrations.CreateModel(
            name='ArrivalEnquiry',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason_code', models.CharField(choices=[('NO_CLINICIAN', 'No clinician'), ('SERVICE_UNAVAILABLE', 'Service unavailable'), ('PRICE', 'Price'), ('REFERRED_OUT', 'Referred out'), ('OTHER', 'Other')], max_length=30)),
                ('occurred_at', models.DateTimeField(default=core.clock.now)),
                ('source_event_id', models.CharField(max_length=120)),
                ('safe_notes', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CONVERTED', 'Converted')], default='OPEN', max_length=20)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_arrival_enquiries', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_arrival_enquiries', to=settings.AUTH_USER_MODEL)),
                ('converted_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrival_enquiries', to='scheduling.visit')),
            ],
        ),
        migrations.AddField(
            model_name='queueentry',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='scheduling.visit'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(condition=models.Q(('visit__isnull', False), ('work_identity__gt', '')), fields=('organisation', 'facility', 'visit', 'queue_type', 'work_identity'), name='uniq_visit_queue_work_identity'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['organisation', 'facility', 'local_service_date', 'state'], name='scheduling__organis_682221_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['organisation', 'patient', 'created_at'], name='scheduling__organis_d3d6d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['OPEN', 'IN_PROGRESS'])), fields=('organisation', 'facility', 'patient', 'local_service_date'), name='uniq_active_visit_patient_facility_day'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('closed_by__isnull', True), ('closure_reason', ''), ('state__in', ['OPEN', 'IN_PROGRESS'])), models.Q(('closed_at__isnull', False), ('closed_by__isnull', False), ('closure_reason__gt', ''), ('state__in', ['CLOSED', 'CANCELLED_ERROR'])), _connector='OR'), name='visit_closure_fields_match_state'),
        ),
        migrations.AddIndex(
            model_name='arrivalenquiry',
            index=models.Index(fields=['organisation', 'facility', 'occurred_at'], name='scheduling__organis_5f7532_idx'),
        ),
        migrations.AddIndex(
            model_name='arrivalenquiry',
            index=models.Index(fields=['organisation', 'facility', 'state'], name='scheduling__organis_17c149_idx'),
        ),
        migrations.AddConstraint(
            model_name='arrivalenquiry',
            constraint=models.UniqueConstraint(fields=('organisation', 'source_event_id'), name='uniq_arrival_enquiry_org_source'),
        ),
        migrations.AddConstraint(
            model_name='arrivalenquiry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('converted_at__isnull', True), ('converted_by__isnull', True), ('converted_visit__isnull', True), ('state', 'OPEN')), models.Q(('converted_at__isnull', False), ('converted_by__isnull', False), ('converted_visit__isnull', False), ('state', 'CONVERTED')), _connector='OR'), name='arrival_enquiry_conversion_fields_match_state'),
        ),
        migrations.RunPython(apply_rls, reverse_rls),
    ]
