#!/usr/bin/env python3
"""Generate the small OpenAPI client base from the Django schema without network access."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys


HEADER = """/* AUTO-GENERATED by tools/generate_api_client.py. Do not edit by hand. */

"""


def schema_for(root: Path):
    backend = root / "backend"
    sys.path.insert(0, str(backend))
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "clinicopus.settings")
    import django

    django.setup()
    from rest_framework.schemas.openapi import SchemaGenerator

    return SchemaGenerator(
        title="KlinKlik API",
        description="KlinKlik Clinic Management API",
        version="1.0",
    ).get_schema(request=None, public=True)


def render(schema):
    operations = []
    for path, item in sorted((schema or {}).get("paths", {}).items()):
        for method, operation in sorted(item.items()):
            if method.lower() not in {
                "get",
                "post",
                "put",
                "patch",
                "delete",
                "head",
                "options",
            }:
                continue
            operations.append(
                {
                    "method": method.upper(),
                    "operationId": operation.get("operationId", ""),
                    "path": path,
                }
            )
    operations_json = json.dumps(operations, ensure_ascii=True, indent=2)
    return (
        HEADER
        + "export type GeneratedApiError = {\n"
        + "  code?: string;\n"
        + "  detail?: string;\n"
        + "  [key: string]: unknown;\n"
        + "};\n\n"
        + "export type GeneratedRequestOptions = RequestInit & {\n"
        + "  idempotencyKey?: string;\n"
        + "  facilityId?: string;\n"
        + "  ifMatch?: string;\n"
        + "};\n\n"
        + "export const GENERATED_API_OPERATIONS = "
        + operations_json
        + " as const;\n\n"
        + "export class GeneratedApiClient {\n"
        + "  constructor(private readonly baseUrl = \"\") {}\n\n"
        + "  async request<T>(path: string, options: GeneratedRequestOptions = {}): Promise<T> {\n"
        + "    const { idempotencyKey, facilityId, ifMatch, ...requestInit } = options;\n"
        + "    const headers = new Headers(requestInit.headers);\n"
        + "    headers.set(\"Content-Type\", \"application/json\");\n"
        + "    if (idempotencyKey) headers.set(\"Idempotency-Key\", idempotencyKey);\n"
        + "    if (facilityId) headers.set(\"X-Facility-Id\", facilityId);\n"
        + "    if (ifMatch) headers.set(\"If-Match\", ifMatch);\n"
        + "    const response = await fetch(this.baseUrl + path, {\n"
        + "      ...requestInit,\n"
        + "      headers,\n"
        + "      credentials: \"include\",\n"
        + "    });\n"
        + "    const text = await response.text();\n"
        + "    const data = text ? (JSON.parse(text) as T | GeneratedApiError) : null;\n"
        + "    if (!response.ok) throw new Error((data as GeneratedApiError)?.detail || \"Request failed.\");\n"
        + "    return data as T;\n"
        + "  }\n"
        + "}\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("frontend/src/generated/api-client.ts"),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    output = args.output if args.output.is_absolute() else root / args.output
    rendered = render(schema_for(root))
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != rendered:
            print(f"FAIL: generated client is stale: {output}")
            return 1
        print(f"PASS: generated client matches the OpenAPI schema ({output}).")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"GENERATED: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
