# Generated by Django 5.2.17 on 2026-09-03 23:34

import core.models
import django.db.models.deletion
from django.db import migrations, models


def apply_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE core_numbersequence ENABLE ROW LEVEL SECURITY;"
            "ALTER TABLE core_numbersequence FORCE ROW LEVEL SECURITY;"
            "DROP POLICY IF EXISTS clinicopus_tenant_isolation ON core_numbersequence;"
            "CREATE POLICY clinicopus_tenant_isolation ON core_numbersequence "
            "USING (organisation_id = current_setting('app.current_org_id')::uuid) "
            "WITH CHECK (organisation_id = current_setting('app.current_org_id')::uuid);"
        )


def reverse_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "DROP POLICY IF EXISTS clinicopus_tenant_isolation ON core_numbersequence;"
            "ALTER TABLE core_numbersequence NO FORCE ROW LEVEL SECURITY;"
            "ALTER TABLE core_numbersequence DISABLE ROW LEVEL SECURITY;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_s00_verification_foundation'),
        ('tenancy', '0003_s01_registration_visit_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_key', models.CharField(max_length=120)),
                ('sequence_type', models.CharField(max_length=80)),
                ('period_key', models.CharField(max_length=40)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='number_sequences', to='tenancy.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenancy.organisation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'scope_key', 'sequence_type', 'period_key'), name='uniq_number_sequence_scope_type_period'), models.CheckConstraint(condition=models.Q(('next_value__gt', 0)), name='number_sequence_next_value_positive')],
            },
        ),
        migrations.RunPython(apply_rls, reverse_rls),
    ]
