# Generated by Django 5.2.17 on 2026-09-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_s00_facility_workflow_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityworkflowpolicy',
            name='consultation_payment_timing',
            field=models.CharField(choices=[('PAY_AFTER', 'Pay after consultation'), ('PAY_BEFORE_TRIAGE', 'Pay before triage')], default='PAY_AFTER', max_length=30),
        ),
    ]
